#!/bin/bash

function set_script_dir() {
  local ORIG_DIR="$(pwd)" || return 1

  local REL_SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})" || return 1
  cd "${REL_SCRIPT_DIR}" || return 1
  SCRIPT_DIR="$(pwd)" || return 1
  cd "${ORIG_DIR}" || return 1
}

function build_library() {
  local ORIG_DIR="$(pwd)" || return 1
  cd "${SCRIPT_DIR}" || return 1

  local URI='https://github.com/jeffdaily/parasail.git'
  local VERSION='v2.6.2'
  git clone "${URI}" || return 1
  cd parasail || return 1
  git checkout "${VERSION}" || return 1
  mkdir build || return 1
  cd build || return 1
  cmake .. || return 1
  make || return 1

  cd "${ORIG_DIR}" || return 1
}

# perl may have been built against xlocale.h.
# xlocale.h was removed in glibc 2.26: https://github.com/conda-forge/perl-feedstock/issues/28
# locale.h can be used instead.
function ensure_xlocale() {
  local TMP_FILE="${SCRIPT_DIR}/temp_file_to_check_header.c"
  local TMP_OUT="${SCRIPT_DIR}/temp_file_to_check_header.out"
  echo '#include <xlocale.h>' > "${TMP_FILE}" || return 1
  gcc -H -fsyntax-only "${TMP_FILE}" 2>/dev/null
  local RETURN_CODE="$?"
  if [[ "${RETURN_CODE}" -eq 0 ]]; then
    # xlocale is found
    rm "${TMP_FILE}" || return 1
    return 0
  fi

  echo '#include <locale.h>' > "${TMP_FILE}" || return 1
  gcc -H -fsyntax-only "${TMP_FILE}" 2> "${TMP_OUT}"
  local RETURN_CODE="$?"
  rm "${TMP_FILE}" || return 1
  if [[ "${RETURN_CODE}" -ne 0 ]]; then
    # locale not found
    echo 'neither xlocale.h or locale.h found' >&2
    rm "${TMP_OUT}" || return 1
    return 1
  fi

  local LOCALE_H_PATH=$(cut -d ' ' -f 2 "${TMP_OUT}" | head -n 1)
  local RETURN_CODE="$?"
  rm "${TMP_OUT}" || return 1
  if [[ "${RETURN_CODE}" -ne 0 ]]; then
    echo 'could not parse locale.h location' >&2
    return 1
  fi

  local LINK_PATH="${SCRIPT_DIR}/xlocale.h"
  if [[ -f "${LINK_PATH}" ]]; then
    rm "${LINK_PATH}" || return 1
  fi

  ln -s "${LOCALE_H_PATH}" "${LINK_PATH}" || return 1
}

function build_module() {
  local ORIG_DIR="$(pwd)" || return 1
  cd "${SCRIPT_DIR}" || return 1

  local PARASAIL_BUILD_SO_PATH="./parasail/build/libparasail.so"
  local PARASAIL_HEADER="./parasail/parasail.h"
  cp "${PARASAIL_BUILD_SO_PATH}" ./ || return 1
  cp "${PARASAIL_HEADER}" ./ || return 1

  ensure_xlocale || return 1
  perl Makefile.PL || return 1
  make || return 1
  cp libparasail.so ./blib/lib/ || return 1
  make test || return 1
  cp ./blib/lib/Parasail.pm ../ || return 1
  cp ./blib/arch/auto/Parasail/Parasail.so ../ || return 1
  cp ./libparasail.so ../ || return 1

  cd "${ORIG_DIR}" || return 1
}

function main() {
  set_script_dir || return 1
  build_library || return 1
  build_module || return 1
}

main "$@"
